@startuml
'https://plantuml.com/class-diagram

note "監査カラムの記述は割愛" as n1

class users {
  id: int
  name: string
  phone_number: string
}
note right: ユーザー

class orders {
  id: int
  user_id: int
  paid: boolean
  ordered_at: datetime
}
note right: 注文

class order_set_menus {
  order_id: int
  set_menu_id: int
  wasabi_removal: boolean
}
note right: 注文とセットメニューの\n中間テーブル（N:N）

class order_sushi {
  order_id: int
  sushi_id: int
  wasabi_removal: boolean
}
note right: 注文と寿司の中間テーブル（N:N）

class order_set_menus_options {
  order_id: int
  set_menu_id: int
  wasabi_removal: boolean
  size_of_shari: int
}
note bottom: 注文ごとのセットメニューのオプション

class order_sushi_options {
  order_id: int
  set_menu_id: int
  wasabi_removal: boolean
  size_of_shari: int
}
note bottom: 注文ごとの寿司のオプション

class set_menus {
  id: int
  name: string
  price: int
  tax_included: boolean
}
note right: セットメニュー

class sushi {
  id: int
  name: string
  price: int
  tax_included: boolean
}
note right: 寿司

users ||--o{ orders
orders ||--o{ order_set_menus
orders ||--o{ order_sushi
order_set_menus }o--|| set_menus
order_sushi }o--|| sushi
order_set_menus ||--|| order_set_menus_options
order_sushi ||--|| order_sushi_options

@enduml